includes:
- config/base_boxer2d_detection.yaml

dataset_config:
  detection:
    use_mask: true

model_config:
  boxer2d:
    use_mask: true
    loss:
      params:
        dice_loss_coef: 5
        mask_loss_coef: 5
        use_mask: ${model_config.boxer2d.use_mask}
    backbone:
      type: resnet101

scheduler:
  type: multi_step
  params:
    use_warmup: true
    mode: iter
    lr_ratio: 0.1
    lr_steps:
    - 210000
    - 250000
    warmup_iterations: 1000
    warmup_factor: 0.001

training:
  max_update: 270000
  iou_type:
  - bbox
  - segm