dataset_config:
  detection:
    use_mask: false
    cache_mode: false
    imdb_files:
      train:
        anno_file: coco/annotation/instances_train2017.json
        image_folder: coco/image/train2017
      val:
        anno_file: coco/annotation/instances_val2017.json
        image_folder: coco/image/val2017
      test:
        anno_file: coco/annotation/image_info_test-dev2017.json
        image_folder: coco/image/test2017
    processors:
      answer_processor:
        type: answer
        params:
          class_file: coco/vocabs/coco_categories.txt
      image_train_processor:
        type: compose
        params:
          preprocessors:
            - type: random_horizontal_flip
              params:
                prob: 0.5
            - type: random_select
              params:
                preprocessors:
                  - type: random_resize
                    params:
                      max_size: 1333
                      min_size:
                        - 480
                        - 801
                        - 32
                  - type: compose
                    params:
                      preprocessors:
                        - type: random_resize
                          params:
                            min_size:
                              - 400
                              - 601
                              - 100
                        - type: random_size_crop
                          params:
                            min_size: 384
                            max_size: 600
                        - type: random_resize
                          params:
                            max_size: 1333
                            min_size:
                              - 480
                              - 801
                              - 32
                probs:
                  - 0.5
                  - 0.5
            - type: to_tensor
              params: {}
            - type: normalize
              params:
                mean:
                  - 0.485
                  - 0.456
                  - 0.406
                std:
                  - 0.229
                  - 0.224
                  - 0.225
      image_test_processor:
        type: compose
        params:
          preprocessors:
            - type: random_resize
              params:
                max_size: 1333
                min_size: 800
            - type: to_tensor
              params: {}
            - type: normalize
              params:
                mean:
                  - 0.485
                  - 0.456
                  - 0.406
                std:
                  - 0.229
                  - 0.224
                  - 0.225

model_config:
  boxer2d:
    hidden_dim: 256
    aux_loss: true
    deform_lr_multi: 0.1
    use_mask: false
    ref_size: 4
    loss:
      type: boxer2d
      params:
        bbox_loss_coef: 5
        giou_loss_coef: 2
        class_loss_coef: 2
        use_mask: ${model_config.boxer2d.use_mask}
        matcher:
          type: hungarian
          params:
            class_weight: ${model_config.boxer2d.loss.params.class_loss_coef}
            bbox_weight: ${model_config.boxer2d.loss.params.bbox_loss_coef}
            giou_weight: ${model_config.boxer2d.loss.params.giou_loss_coef}
            focal_label: true
    metric:
      - type: accuracy
        params: {}
    backbone:
      type: resnet50
      params:
        pretrained: true
        pretrained_path: null
        freeze_backbone: null
        position_encoding: fixed_box
        return_interm_layers:
          - layer2
          - layer3
          - layer4
        hidden_dim: ${model_config.boxer2d.hidden_dim}
        ref_size: ${model_config.boxer2d.ref_size}
    transformer:
      type: box_transformer
      params:
        hidden_dim: ${model_config.boxer2d.hidden_dim}
        nhead: 8
        nlevel: 4
        enc_layers: 6
        dec_layers: 6
        dim_feedforward: 1024
        dropout: 0
        num_queries: 300
        use_mask: ${model_config.boxer2d.use_mask}
        ref_size: ${model_config.boxer2d.ref_size}
        residual_mode: v1

optimizer:
  type: adamw
  params:
    lr: 2.0e-4
    lr_backbone: 2.0e-5
    use_oss: false
    weight_decay: 1.0e-4
    eps: 1.0e-09
    betas:
      - 0.9
      - 0.999

training:
  batch_size: 16
  iter_per_update: 1
  find_unused_parameters: false
  tensorboard: false
  evaluation_interval: 1
  checkpoint_interval: 1
  log_interval: 200
  max_norm: 0.1
  run_type: train_val
  iou_type:
    - bbox
